### ISSUE TITLE
classifier.group_articles returning abnormally long grouped lists of len > 417

### ISSUE THREAD

**Issue by masonshuler** [mmw125/MuDimA#27]
_______________ RigerousClassifierTest.test_classifier_grouping ________________

self = <server.classifier_test.RigerousClassifierTest testMethod=test_classifier_grouping>

    def test_classifier_grouping(self):
        self.concat_articles = self.hurricane_harvy_urls + self.tom_petty_urls + self.las_vegas_urls
>       self.assertEqual(3, len(classifier.group_articles(self.concat_articles)))
E       AssertionError: 3 != 418

server/classifier_test.py:49: AssertionError
__________________ FindURLErrorTest.test_keywordless_articles __________________

self = <server.classifier_test.FindURLErrorTest testMethod=test_keywordless_articles>

    def test_keywordless_articles(self):
        """Tests that keywordless articles are put into a separate grouping."""
        articles = [models.Article(url="example.com", keywords=[]), models.Article(url="test.com", keywords=[])]
        articles.extend(test_utils.SIMILAR_ARTICLES)
        groups = classifier.group_articles(articles)
>       self.assertEqual(2, len(groups))
E       AssertionError: 2 != 418

server/classifier_test.py:67: AssertionError
_____________________ FindURLErrorTest.test_parsing_issue ______________________

self = <server.classifier_test.FindURLErrorTest testMethod=test_parsing_issue>

    def test_parsing_issue(self):
>       self.assertEqual(1, len(classifier.group_articles(self.url)))
E       AssertionError: 1 != 417

server/classifier_test.py:58: AssertionError

**Comment by mmw125** [comment]
I think this is because you are overriding the setUp method defined in test_utils.DatabaseTest. This causes the database to not be refreshed on each test.

**Comment by masonshuler** [comment]
On it thanks
