### ISSUE TITLE
self.top_headline.get_source().get_id() not returning None when expected

### ISSUE THREAD

**Issue by masonshuler** [mmw125/MuDimA#28]
news_fetcher.get_top_headlines() is reading from the following json

{
      "source": {
        "id": null,
        "name": null
      },
      "author": null,
      "title": null,
      "description": null,
      "url": null,
      "urlToImage": null,
      "publishedAt": null
    },

>       self.assertEqual(self.top_headline.get_source().get_id(), None)
E       AssertionError: u'the-next-web' != None

**Comment by mmw125** [comment]
Can you provide more context for this?
