### ISSUE TITLE
Grab favicons for all sorces

### ISSUE THREAD

**Issue by masonshuler** [mmw125/MuDimA#53]
grab favicons from each source for front end display

www.url.com/favicon.ico

**Comment by masonshuler** [comment]
can someone check out the favicon branch?

**Comment by mmw125** [comment]
I looked at it and made some commits to the branch. I saw that the newspaper API was providing the link to the favicon most of the time. So now I'm storing the links to the favicons in the articles table in the database.

**Comment by mmw125** [comment]
#60
